name: publish jqmc gh-pages

on:
  push:
    branches: [rc-gh-pages]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        python-version: 3.11
        activate-environment: rc-gh-pages

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -y -c conda-forge sphinx-book-theme linkify-it-py myst-parser sphinxcontrib-bibtex ipython pip
        python -m pip install -e . --no-deps

    - name: Build
      shell: bash -l {0}
      run: |
        sphinx-apidoc -o doc/ jqmc/
        sphinx-build doc docs_build

    - name: Deploy docs at develop branch
      if: ${{ github.ref == 'refs/heads/rc-gh-pages' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_build
