# This workflow will build and test jqmc.

name: jqmc build and test

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Install jqmc
      run: |
        python -m pip install flake8 pytest
        python -m pip install .

    - name: Lint jqmc with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test jqmc with pytest
      run: |
        pytest
